export const HELPER_PKG_PATH = 'components/vibeview/vibeview.brs';
export const HELPER_URI = `pkg:/${HELPER_PKG_PATH}`;

const ENABLED = `' Generated by vibeview-bsc-plugin. Mirrors highlight state, test ids and labels
' into a hidden Label (id "vibeviewMarker") that Roku's ECP app-ui dump shows.

' Marker text: "vv" then tokens "focused", "id=<id>" and, always last, "label=<text>"
' (the label may contain spaces). focused/id/label invalid = keep the current value.
function vibeview_tokens(text as String, focused as Dynamic, id as Dynamic, label as Dynamic) as String
    curFocused = false
    curId = ""
    curLabel = ""
    head = text
    at = Instr(1, text, " label=")
    if at > 0
        curLabel = Mid(text, at + 7)
        head = Left(text, at - 1)
    end if
    for each t in head.split(" ")
        if t = "focused" then curFocused = true
        if Left(t, 3) = "id=" then curId = Mid(t, 4)
    end for
    if focused <> invalid then curFocused = focused
    if id <> invalid then curId = id
    if label <> invalid then curLabel = label
    out = ""
    if curFocused then out = " focused"
    if curId <> "" then out = out + " id=" + curId
    if curLabel <> "" then out = out + " label=" + curLabel
    if out = "" then return ""
    return "vv" + out
end function

' The node's own marker: a DIRECT child, never one of a nested item's.
function vibeview_marker(node as Object, create as Boolean) as Object
    for each child in node.getChildren(-1, 0)
        if child.id = "vibeviewMarker" then return child
    end for
    if not create then return invalid
    marker = node.createChild("Label")
    marker.id = "vibeviewMarker"
    marker.visible = false
    ' 1x1 so the marker's text never widens the node's bounding rect (a LayoutGroup
    ' parent would otherwise reflow its other children).
    marker.width = 1
    marker.height = 1
    return marker
end function

sub vibeview_setHighlight(node as Object, on as Boolean)
    if node = invalid then return
    marker = vibeview_marker(node, on)
    if marker = invalid then return
    marker.text = vibeview_tokens(marker.text, on, invalid, invalid)
end sub

sub vibeview_setId(node as Object, id as String)
    if node = invalid then return
    if not CreateObject("roRegex", "^[A-Za-z0-9_.\\-]+$", "").isMatch(id)
        print "[vibeview] ignoring invalid test id: "; id
        return
    end if
    marker = vibeview_marker(node, true)
    marker.text = vibeview_tokens(marker.text, invalid, id, invalid)
end sub

' Injected at the top of init(); table is keyed by component name.
sub vibeview_autoMark(table as Object)
    cfg = table[m.top.subtype()]
    if cfg = invalid then return
    if cfg.ids <> invalid
        for each pair in cfg.ids
            vibeview_setId(m.top.findNode(pair[0]), pair[1])
        end for
    end if
    if cfg.field <> invalid and cfg.field <> ""
        m.vibeview_field = cfg.field
        m.top.observeField(cfg.field, "vibeview_onHighlight")
        if m.top.getField(cfg.field) = true then vibeview_setHighlight(m.top, true)
        vibeview_watchIdentity()
    end if
end sub

sub vibeview_onHighlight()
    vibeview_setHighlight(m.top, m.top.getField(m.vibeview_field) = true)
end sub

' Observe the first segment of every id/label path so recycled items follow
' their new content, then compute the identity once now.
sub vibeview_watchIdentity()
    cfg = vibeview_identityConfig()
    seen = {}
    for each path in cfg.ids
        seen[path.split(".")[0]] = true
    end for
    for each path in cfg.labels
        seen[path.split(".")[0]] = true
    end for
    for each field in seen
        if m.top.hasField(field) then m.top.observeField(field, "vibeview_onIdentity")
    end for
    vibeview_onIdentity()
end sub

' First non-empty string (or integer, as text) among the paths, else "".
function vibeview_firstValue(paths as Object) as String
    for each path in paths
        parts = path.split(".")
        v = invalid
        if m.top.hasField(parts[0]) then v = m.top.getField(parts[0])
        if parts.count() = 2
            if Type(v) = "roSGNode" and v.hasField(parts[1]) then v = v.getField(parts[1]) else v = invalid
        end if
        t = Type(v)
        if t = "roString" or t = "String"
            if v <> "" then return v
        else if t = "roInt" or t = "Integer" or t = "roLongInteger" or t = "LongInteger"
            return v.ToStr()
        end if
    end for
    return ""
end function

sub vibeview_onIdentity()
    cfg = vibeview_identityConfig()
    if cfg.ids.count() = 0 and cfg.labels.count() = 0 then return
    idv = CreateObject("roRegex", "[^A-Za-z0-9_.\\-]", "").ReplaceAll(vibeview_firstValue(cfg.ids), "_")
    idv = Left(idv, 64)
    lbl = CreateObject("roRegex", "[\\r\\n]+", "").ReplaceAll(vibeview_firstValue(cfg.labels), " ")
    lbl = Left(lbl, 80)
    marker = vibeview_marker(m.top, idv <> "" or lbl <> "")
    if marker = invalid then return
    ' A field-derived id never replaces an explicit one (vibeviewId / vibeview_setId).
    curId = ""
    head = marker.text
    at = Instr(1, head, " label=")
    if at > 0 then head = Left(head, at - 1)
    for each t in head.split(" ")
        if Left(t, 3) = "id=" then curId = Mid(t, 4)
    end for
    newId = invalid
    if m.vibeview_fieldId = invalid then m.vibeview_fieldId = ""
    if curId = "" or curId = m.vibeview_fieldId
        newId = idv
        m.vibeview_fieldId = idv
    end if
    marker.text = vibeview_tokens(marker.text, invalid, newId, lbl)
end sub
`;

const DISABLED = `' Generated by vibeview-bsc-plugin (markers disabled): markup calls do nothing.

sub vibeview_setHighlight(node as Object, on as Boolean)
end sub

sub vibeview_setId(node as Object, id as String)
end sub
`;

export function helperScript(
  enabled: boolean,
  identity: { idFields: string[]; labelFields: string[] } = { idFields: [], labelFields: [] },
): string {
  if (!enabled) return DISABLED;
  const list = (xs: string[]) => `[${xs.map((x) => JSON.stringify(x)).join(', ')}]`;
  return `${ENABLED}
' Configured id/label paths (vibeview.idFields / vibeview.labelFields).
function vibeview_identityConfig() as Object
    return {ids: ${list(identity.idFields)}, labels: ${list(identity.labelFields)}}
end function
`;
}
